/oak:
  ros__parameters:
    camera:
      i_nn_type: spatial
      i_fps: 30.0
    stereo:
      i_subpixel: true
    rgb:
      i_enable_preview: true
      i_preview_size: 320
      i_keep_preview_aspect_ratio: false
    nn:
      i_enable_passthrough: true
      i_disable_resize: true
      i_nn_config_path: depthai_ros_driver/yolo
/spatial_bb_node:
  ros__parameters:
    desqueeze: true
    label_map: ["obstacle"]
/detection_overlay_node:
  ros__parameters:
    label_map: ["obstacle"]

