/**:
  ros__parameters:
    wheel_radius: 0.29
    wheel_width: 0.29
    wheel_base: 2.9718 # between front wheel center and rear wheel center
    wheel_tread: 1.6 # between left wheel center and right wheel center
    front_overhang: 0.9 # between front wheel center and vehicle front
    rear_overhang: 0.7 # between rear wheel center and vehicle rear
    left_overhang: 0.1 # between left wheel center and vehicle left
    right_overhang: 0.1 # between right wheel center and vehicle right
    vehicle_height: 1.2573
    max_steer_angle: 0.2513274  # [rad]